import { Router } from "express";
import {getAllBooks,getSpecificBook,addBook,deleteBook,updateBook,borrwAndReturn} from'../controllers/book.controller.js';
import { generalLimiter } from "../middlewares/mainMiddlewares.js";
const router = Router();
router.use(generalLimiter);
router.get('/',getAllBooks);
router.get('/:code',getSpecificBook);
router.post('/',addBook);
router.delete('/:code',deleteBook);
router.put('/:code',updateBook);
router.patch('/:code',borrwAndReturn);
export default router;